// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsnSnnLiR-ieQMqvnCgn1ZF82U9ChE3Oo',
    appId: '1:773494367421:web:2b87faea363143b4ea43d4',
    messagingSenderId: '773494367421',
    projectId: 'bamx-app-1c2b2',
    authDomain: 'bamx-app-1c2b2.firebaseapp.com',
    storageBucket: 'bamx-app-1c2b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEKrRw-GKy1mQsnNM15FQN8IyUWQgLPAk',
    appId: '1:773494367421:android:6371a649aa835d6aea43d4',
    messagingSenderId: '773494367421',
    projectId: 'bamx-app-1c2b2',
    storageBucket: 'bamx-app-1c2b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZ0ebDaeRcV44JFcIUW9dG0GYGch0Xmg',
    appId: '1:773494367421:ios:69981e25fc0eef70ea43d4',
    messagingSenderId: '773494367421',
    projectId: 'bamx-app-1c2b2',
    storageBucket: 'bamx-app-1c2b2.appspot.com',
    iosBundleId: 'com.example.bamxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtZ0ebDaeRcV44JFcIUW9dG0GYGch0Xmg',
    appId: '1:773494367421:ios:7fec7327bc9c9658ea43d4',
    messagingSenderId: '773494367421',
    projectId: 'bamx-app-1c2b2',
    storageBucket: 'bamx-app-1c2b2.appspot.com',
    iosBundleId: 'com.example.bamxApp.RunnerTests',
  );
}
